import Navigation from '@/components/navigation';
import './globals.css';
import SessionProvider from '@/components/session-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navigation />
          <main>
            <div>
              {children}
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
